Upgrade grid editor to work with Python 3.10.
Python 3.10 no longer auto-truncates floats to ints
on the C backend. This caused errors when opening
the grid editor (which uses a wx backend) along
the lines of:

    [CRIT 000 ] Stack trace: Traceback (most recent call last):
      File "/home/nick/code/armi2/armi/__main__.py", line 34, in main
        code = ArmiCLI().run()
      File "/home/nick/code/armi2/armi/cli/__init__.py", line 201, in run
        return self.executeCommand(args.command, args.args)
      File "/home/nick/code/armi2/armi/cli/__init__.py", line 230, in executeCommand
        return cmd.invoke()
      File "/home/nick/code/armi2/armi/cli/gridGui.py", line 56, in invoke
        gui = gridEditor.GridBlueprintControl(frame)
      File "/home/nick/code/armi2/armi/utils/gridEditor.py", line 1247, in __init__
        self.clicker = GridGui(self, defaultGeom=self._defaultGeom)
      File "/home/nick/code/armi2/armi/utils/gridEditor.py", line 755, in __init__
        self.drawGrid()
      File "/home/nick/code/armi2/armi/utils/gridEditor.py", line 881, in drawGrid
        rect = self._calcGridBounds()
      File "/home/nick/code/armi2/armi/utils/gridEditor.py", line 1217, in _calcGridBounds
        return wx.Rect(wx.Point(*topLeft[:2]), wx.Point(*bottomRight[:2]))
    TypeError: Point(): arguments did not match any overloaded call:
      overload 1: too many arguments
      overload 2: argument 1 has unexpected type 'numpy.float64'
      overload 3: argument 1 has unexpected type 'numpy.float64'
      overload 4: argument 1 has unexpected type 'numpy.float64'

This change explicitly changes all arguments of wx.Point to integers
before passing in to solve this issue.

Relatedly, the outlines were not being shown, as the numpy arrays were
no longer being properly cast to wx.Points. Thus, this explicitly builds
the polygons as lists of wx.Points to solve that problem as well.

With these changes, the grid editor works in Python 3.10 as expected.