Implement MultiIndexLocation.getLocalCoordinates
There were some errors raised in the invocation of _evaluateMesh
only expecting a single entry, errors like
```
    result[self._stepDims] = stepCoords
    ValueError: shape mismatch: value array of shape (3,3) could not be broadcast to indexing result of shape (3,)
```
Now, `MultiIndex.getLocationCoordinates` will produce the local coords for everything
contained in the index.

And a test is added. so that's good!